#!/usr/bin/env python3


import csv


def tsv(filename):
    with open(filename, "r") as f:
        return list(
            csv.reader(f, delimiter="\t")
        )


def tabdicts(table):
    table = list(table)
    columns = table[0]
    for row in table[1:]:
        yield dict(
            zip(columns, row)
        )


def tsv_dicts(fn):
    return tabdicts(
        tsv(fn)
    )
